# Aggressive Security Strategy  
# Immediate security fixes regardless of breaking changes
name: "aggressive_security"
description: "Immediate security fixes regardless of breaking changes"

# All security issues are high priority
severity_priorities:
  critical: "immediate"
  high: "immediate"         # Treat HIGH as IMMEDIATE
  medium: "high"
  low: "medium"

# Allow any changes needed for security
upgrade_constraints:
  max_version_jump: "any"         # Major version jumps OK
  allow_breaking_changes: true    # Accept breaking changes
  max_effort_level: "complex"     # Accept complex upgrades
  prefer_stable_releases: false   # Use latest versions

# Advanced configuration for high-security environments
minimum_fix_threshold: null       # Fix everything
batch_upgrades_preferred: false   # Fix immediately, don't batch
zero_downtime_required: false     # Downtime acceptable for security
compliance_mode: true             # Enable compliance tracking